### ISSUE TITLE
Data processing and dataset

### ISSUE THREAD

**Issue by HBioquant** [MatthewMasters/EDM-Dock#2]
Hi, are there any data processing and data spliting scripts available? I have confusion about the complex structures filtering from PDBBindv2020 and BioLip: Why did you remove ligands binding with multiple chains, even if their percentage is relatively small from your reported number in SI? I have downloaded the released dataset (without data spliting), and I found thousands of mol2 files is invalid after rdkit loading (rdkit version 2022.09.5)， although using schrodinger-2021 to convert the mol2 file to sdf file, there are still 1738 sdf files failed. How did you solve it? Or can you update the released dataset?
Thanks,
David

**Comment by OnlyEpisode** [comment]
The same request~

**Comment by zetayue** [comment]
I also have questions about the training set provided at https://doi.org/10.5281/zenodo.7233024. It seems that the provided training set doesn't match the filtering criteria mentioned in SI.

For example, the training set contains complexes like `1a1b` that has peptide. Besides, the training set contains complexes like `3rwm-GNP-B-2` that has site with < 20 residuals.

**Comment by MatthewMasters** [comment]
Sorry for the delayed response here. To answer your questions: the criteria to remove binding sites with multiple chains came from an earlier development where we explored pre-trained protein sequence embeddings and needed to isolate the problem to single chains. It is possible that including these training examples could further improve the model. For the molecules you are unable to load into RDKit, could you provide a specific example? I was able to load every molecule as either mol2 or sdf (converted using OpenBabel).
