### ISSUE TITLE
DGSOL alternatives

### ISSUE THREAD

**Issue by isty2e** [MatthewMasters/EDM-Dock#3]
There have been several advancements over DGSOL for the molecular geometry problem. One of such examples is https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-14-S9-S7, which the authors claim to be superior to DGSOL. Assuming the model-predicted EDM is likely to be somewhat noisy, I suppose this algorithm can serve as a potentially better alternative.

**Comment by MatthewMasters** [comment]
Sorry for the late response here. Thank you very much for this info. This algorithm does seem to be a great choice for this problem. I will consider using it for any further developments :)
