### ISSUE TITLE
Weird docked pose for generated molecule

### ISSUE THREAD

**Issue by qky18** [MatthewMasters/EDM-Dock#4]
Hi, many thanks for sharing this great work! 
I was trying to predict binding pose for some DL-method generated molecule like this:

![image](https://github.com/MatthewMasters/EDM-Dock/assets/48824043/0fc1d178-efef-445d-a603-e353a6f4e84d)

whose smiles is `CN1C=NC2=C(C1)O[C@H](C1=C[C@@H](O)C=C[C@H]1O)[C@H]2CC[C@@H](O)C(=O)O`.

However, it was found that after EDM prediction and DGSOL alignment, the conformation for this molecule turned from left to right, which is probably not correct since the atoms of neither the five- nor six-member ring are coplanar.
<img width="358" alt="image" src="https://github.com/MatthewMasters/EDM-Dock/assets/48824043/e080646b-a961-424d-8945-c31ef2f50fbd"><img width="391" alt="image" src="https://github.com/MatthewMasters/EDM-Dock/assets/48824043/4738b6df-2283-4649-8691-115f572660bd">

I was wondering what might be causing this problem, and how may I fix it? Thanks in advance!

**Comment by MatthewMasters** [comment]
Sorry for the late response here. EDM-Dock does not incorporate physical priors such as aromatic ring planarity and simply tries to satisfy various distance constraints. So artifacts like this are expected to occur occasionally
